// Generated by CIRCT unknown git version
module cnt(	// /app/python/assassyn/pycde_wrapper.py:143
  input         clk,
                rst,
                w_port0,
                widx_port0,
  input  [31:0] wdata_port0,
  output [31:0] rdata_port0,
                rdata_port1
);

  wire [31:0]      _GEN;	// /app/python/assassyn/pycde_wrapper.py:122
  reg  [0:0][31:0] _GEN_0;	// /app/python/assassyn/pycde_wrapper.py:111
  always_ff @(posedge clk) begin	// /app/python/assassyn/pycde_wrapper.py:111
    if (rst)	// /app/python/assassyn/pycde_wrapper.py:111
      _GEN_0 <= '{32'h0};	// /app/python/assassyn/pycde_wrapper.py:111
    else	// /app/python/assassyn/pycde_wrapper.py:111
      _GEN_0[1'h0] <= w_port0 & ~widx_port0 ? wdata_port0 : _GEN;	// /app/python/assassyn/pycde_wrapper.py:122, :127, :128, :131
  end // always_ff @(posedge)
  assign _GEN = _GEN_0[/*Zero width*/ 1'b0];	// /app/python/assassyn/pycde_wrapper.py:111, :122
  assign rdata_port0 = _GEN;	// /app/python/assassyn/pycde_wrapper.py:99, :122
  assign rdata_port1 = _GEN;	// /app/python/assassyn/pycde_wrapper.py:99, :122
endmodule

