// Generated by CIRCT unknown git version
module Driver(	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:21
  input         clk,
                rst,
  input  [63:0] cycle_count,
  input         trigger_counter_pop_valid,
  input  [31:0] cnt_rdata_port0,
                cnt_rdata_port1,
  output        executed,
                finish,
                cnt_w_port0,
  output [31:0] cnt_wdata_port0,
  output        cnt_widx_port0,
  output [31:0] expose_Driver_cnt_rd_1,
  output        valid_Driver_cnt_rd_1
);

  assign executed = trigger_counter_pop_valid;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:36
  assign finish = 1'h0;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:36, :43
  assign cnt_w_port0 = trigger_counter_pop_valid;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:36
  assign cnt_wdata_port0 = cnt_rdata_port0 + 32'h1;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:36, :43
  assign cnt_widx_port0 = 1'h0;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:36, :43
  assign expose_Driver_cnt_rd_1 = cnt_rdata_port1;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:36
  assign valid_Driver_cnt_rd_1 = trigger_counter_pop_valid;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:36
endmodule

