// Generated by CIRCT unknown git version
module Top(	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:62
  input         clk,
                rst,
  output [63:0] global_cycle_count,
  output        global_finish
);

  wire        _Driver_executed;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:99
  wire        _Driver_cnt_w_port0;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:99
  wire [31:0] _Driver_cnt_wdata_port0;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:99
  wire        _TriggerCounterImpl_pop_valid;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:93
  wire [31:0] _cnt_rdata_port0;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:88
  wire [31:0] _cnt_rdata_port1;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:88
  reg  [63:0] _GEN;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:73
  always_ff @(posedge clk) begin	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:73
    if (rst)	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:73
      _GEN <= 64'h0;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:73
    else	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:73
      _GEN <= _GEN + 64'h1;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:73, :74
  end // always_ff @(posedge)
  cnt cnt (	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:88
    .clk         (clk),
    .rst         (rst),
    .w_port0     (_Driver_cnt_w_port0),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:99
    .widx_port0  (1'h0),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:74
    .wdata_port0 (_Driver_cnt_wdata_port0),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:99
    .rdata_port0 (_cnt_rdata_port0),
    .rdata_port1 (_cnt_rdata_port1)
  );	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:88
  trigger_counter #(
    .WIDTH(64'd8)
  ) TriggerCounterImpl (	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:93
    .clk         (clk),
    .rst_n       (~rst),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:93
    .delta       (8'h1),
    .pop_ready   (_Driver_executed),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:99
    .delta_ready (/* unused */),
    .pop_valid   (_TriggerCounterImpl_pop_valid)
  );	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:93
  Driver Driver (	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:99
    .clk                       (clk),
    .rst                       (rst),
    .cycle_count               (_GEN),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:73
    .trigger_counter_pop_valid (_TriggerCounterImpl_pop_valid),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:93
    .cnt_rdata_port0           (_cnt_rdata_port0),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:88
    .cnt_rdata_port1           (_cnt_rdata_port1),	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:88
    .executed                  (_Driver_executed),
    .finish                    (/* unused */),
    .cnt_w_port0               (_Driver_cnt_w_port0),
    .cnt_wdata_port0           (_Driver_cnt_wdata_port0),
    .cnt_widx_port0            (/* unused */),
    .expose_Driver_cnt_rd_1    (/* unused */),
    .valid_Driver_cnt_rd_1     (/* unused */)
  );	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:99
  assign global_cycle_count = _GEN;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:68, :73
  assign global_finish = 1'h0;	// /home/tomorrow_arc1/CS/assassyn/MyCPU/workspace/driver/verilog/design.py:68, :74
endmodule

